source 'https://rubygems.org'

gem 'sinatra', '1.4.4'
gem 'warbler', '~> 1.4.0'
gem 'rack', '1.5.2'
gem 'rake'

group :development, :test do
  gem 'pry'
  gem 'pry-nav'
end

group :development do
  gem 'jetty-rackup'
  gem 'racksh'
end

group :test do
  gem 'rspec'
  gem 'rack-test'
end